### ISSUE TITLE
Add every new user to "All users" group

### ISSUE THREAD

**Issue by nimaai** [leihs/zhdk-sync#2]
https://github.com/leihs/leihs/issues/1016

**Comment by nimaai** [comment]
Not sure though, if maybe a DB trigger would be better? It is a universal feature for all leihs instances and we don't want to forget that...

**Comment by eins78** [comment]
> Not sure though, if maybe a DB trigger would be better? It is a universal feature for all leihs instances and we don't want to forget that...

I agree, in Madek there exists both:
* an "all users" group, via a DB trigger (would include all users)
* an "all org users" group, which is managed by the sync (would _not_ include manually managed user accounts)

I think we only need the first option for now, I dont see any use cases in leihs for AuthenticationSystem-specific groups (and if there are in the future we might do it slightly different).

**Comment by nimaai** [comment]
By giving it a second thought, I am not sure anymore. I think the best solution would be to offer a possibility in the UI to add the newly created user to the "all users" group (or any other group for that matter). Maybe this even already exists. 

Let a particular school decide how they manage their users and groups. Maybe some school does not even need or want an "all users" group? I think it goes better with our long term vision of groups, which can be used for different purposes according to the  respective needs. 

I think this is a cleaner and neater solution, though perhaps it needs some form of communication (UI and maybe release notes, etc.) so that the users don't miss it. Otherwise we need a trigger (which is always a little obscure) and some sort of group protection or additional attributes on the groups too maybe.

**Comment by eins78** [comment]
> Let a particular school decide how they manage their users and groups. Maybe some school does not even need or want an "all users" group? I think it goes better with our long term vision of groups, which can be used for different purposes according to the respective needs.

In my view this its very simple: We want this "special" group to *exist* (because its guaranteed to be correct if the system handles it automatically), but then each instance (or pool) can decide if they want to _use_ it. 
And, in my opinion, it a better fit for the long-term vision of using user- and group-based assignments everywhere: We implement this special group once and it can be used whereever it fits, instead of handling the special case of "all users" everywhere (e.g. the authentication-systems dont need a "enable for all users" option, if I can just add the "all users" group.

One more thought: If the group is based on a DB-trigger it would be even nicer to just include the `is_active` users! In practice it does not make a difference for the users access permissions (because they cant login), but for example the members count would be more realistic.

**Comment by nimaai** [comment]
No need to anything here as discussed here: https://github.com/leihs/leihs/pull/1020
